name: mental_health
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  google_sign_in: ^6.2.1
  firebase_storage: ^12.1.0

  # Widgets
  double_back_to_close: ^2.0.0
  liquid_pull_to_refresh: ^3.0.1
  flutter_spinkit: ^5.2.1
  percent_indicator: ^4.2.3

  # Utility Packages
  intl: ^0.19.0
  lottie: ^3.1.2
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.1
  flutter_native_splash: ^2.4.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  file_picker: ^8.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# App Logo
# flutter pub get
# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/app_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/animations/
    - assets/images/logo/
    - assets/images/splash/
    - assets/images/themes/
    - assets/images/members/
    - assets/images/emotions/
    - assets/images/authentication/

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
