// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvv5cPRRcvYj7DwtLtLqDG78wdn-hyQ-g',
    appId: '1:767955934430:android:873a581cd7fec8bc3fb64f',
    messagingSenderId: '767955934430',
    projectId: 'graduationproject-e3eb9',
    storageBucket: 'graduationproject-e3eb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqiEG6-FQF5HmDlfF7NhwpxFRuW59_Hi0',
    appId: '1:767955934430:ios:13d20e3fc0a10f4e3fb64f',
    messagingSenderId: '767955934430',
    projectId: 'graduationproject-e3eb9',
    storageBucket: 'graduationproject-e3eb9.appspot.com',
    androidClientId: '767955934430-6arbnkoialn752nd7ff0fdj07s4glhdq.apps.googleusercontent.com',
    iosClientId: '767955934430-p39v7du4uusd5hhpl2em1l140j4157e6.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

}